# Generated by Django 5.0.7 on 2024-07-10 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoCategoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='talle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='producto.talle'),
            preserve_default=False,
        ),
    ]
