# Generated by Django 5.0.7 on 2024-07-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_delete_productocategoria_producto_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talle',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
